[package]
name = "countme"
version = "0.1.0"
authors = ["Mahdi Zareie <mahdi.elf@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
rayon = {version = "1.3.0"}
threadpool = "1.8.1"
crossbeam-queue = "0.2.1"
regex = "1"
